/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    'storage-items': StorageItem;
    orders: Order;
    'order-events': OrderEvent;
    warehouses: Warehouse;
    cells: Cell;
    tariffs: Tariff;
    subscriptions: Subscription;
    payments: Payment;
    'support-tickets': SupportTicket;
    'support-messages': SupportMessage;
    'integration-events': IntegrationEvent;
    'audit-log': AuditLog;
    'otp-challenges': OtpChallenge;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    'storage-items': StorageItemsSelect<false> | StorageItemsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    'order-events': OrderEventsSelect<false> | OrderEventsSelect<true>;
    warehouses: WarehousesSelect<false> | WarehousesSelect<true>;
    cells: CellsSelect<false> | CellsSelect<true>;
    tariffs: TariffsSelect<false> | TariffsSelect<true>;
    subscriptions: SubscriptionsSelect<false> | SubscriptionsSelect<true>;
    payments: PaymentsSelect<false> | PaymentsSelect<true>;
    'support-tickets': SupportTicketsSelect<false> | SupportTicketsSelect<true>;
    'support-messages': SupportMessagesSelect<false> | SupportMessagesSelect<true>;
    'integration-events': IntegrationEventsSelect<false> | IntegrationEventsSelect<true>;
    'audit-log': AuditLogSelect<false> | AuditLogSelect<true>;
    'otp-challenges': OtpChallengesSelect<false> | OtpChallengesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      'send-otp': TaskSendOtp;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  phone?: string | null;
  firstName?: string | null;
  lastName?: string | null;
  contactEmail?: string | null;
  role: 'client' | 'manager' | 'warehouse' | 'admin';
  active?: boolean | null;
  notifications?: boolean | null;
  paymentBrand?: string | null;
  paymentLast4?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "storage-items".
 */
export interface StorageItem {
  id: string;
  owner: string | User;
  internalID: string;
  title: string;
  type: 'box' | 'item';
  description?: string | null;
  contents?: string | null;
  barcode?: string | null;
  seal?: string | null;
  status: 'expected' | 'received' | 'stored' | 'reserved' | 'picked' | 'returned';
  cell?: (string | null) | Cell;
  monthlyPrice: number;
  startedAt?: string | null;
  media?: (string | Media)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cells".
 */
export interface Cell {
  id: string;
  name: string;
  warehouse: string | Warehouse;
  zone?: string | null;
  barcode: string;
  capacity: number;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "warehouses".
 */
export interface Warehouse {
  id: string;
  name: string;
  address?: string | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  owner: string | User;
  purpose: 'intake' | 'return' | 'signature' | 'document' | 'support';
  prefix?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: string;
  owner: string | User;
  number: string;
  type: 'intake' | 'return';
  status: 'created' | 'received' | 'placed' | 'picking' | 'ready' | 'completed' | 'cancelled';
  items: (string | StorageItem)[];
  fulfillment: 'pickup' | 'courier';
  address?: string | null;
  slot?: string | null;
  assignee?: (string | null) | User;
  picked?: (string | StorageItem)[] | null;
  signature?: (string | null) | Media;
  evidence?: (string | Media)[] | null;
  idempotencyKey: string;
  requestHash?: string | null;
  payment?: (string | null) | Payment;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments".
 */
export interface Payment {
  id: string;
  owner: string | User;
  amount: number;
  status: 'pending' | 'paid' | 'failed' | 'refunded';
  provider?: string | null;
  providerID?: string | null;
  idempotencyKey?: string | null;
  order?: (string | null) | Order;
  tariff?: (string | null) | Tariff;
  receiptURL?: string | null;
  paidAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tariffs".
 */
export interface Tariff {
  id: string;
  name: string;
  code: string;
  kind: 'storage' | 'subscription';
  itemType: 'box' | 'item';
  testOnly?: boolean | null;
  monthlyPrice: number;
  itemLimit: number;
  rules?: string | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order-events".
 */
export interface OrderEvent {
  id: string;
  owner: string | User;
  order: string | Order;
  status: string;
  actor?: (string | null) | User;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriptions".
 */
export interface Subscription {
  id: string;
  owner: string | User;
  tariff: string | Tariff;
  status: 'pending' | 'active' | 'paused' | 'cancelled';
  nextChargeAt?: string | null;
  providerCustomerID?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "support-tickets".
 */
export interface SupportTicket {
  id: string;
  owner: string | User;
  type: 'technical' | 'incident';
  subject: string;
  status: 'submitted' | 'in_progress' | 'resolved';
  order?: (string | null) | Order;
  item?: (string | null) | StorageItem;
  attachments?: (string | Media)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "support-messages".
 */
export interface SupportMessage {
  id: string;
  owner: string | User;
  ticket: string | SupportTicket;
  author: string | User;
  authorRole: 'client' | 'support';
  text: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "integration-events".
 */
export interface IntegrationEvent {
  id: string;
  key: string;
  provider: string;
  status: 'pending' | 'completed' | 'failed';
  externalID?: string | null;
  entityID?: string | null;
  errorCode?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log".
 */
export interface AuditLog {
  id: string;
  actor?: (string | null) | User;
  entity: string;
  entityID: string;
  action: string;
  changedFields?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "otp-challenges".
 */
export interface OtpChallenge {
  id: string;
  phoneKey: string;
  ipKey: string;
  hash: string;
  expiresAt: string;
  attempts: number;
  consumed?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'send-otp';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'send-otp') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'storage-items';
        value: string | StorageItem;
      } | null)
    | ({
        relationTo: 'orders';
        value: string | Order;
      } | null)
    | ({
        relationTo: 'order-events';
        value: string | OrderEvent;
      } | null)
    | ({
        relationTo: 'warehouses';
        value: string | Warehouse;
      } | null)
    | ({
        relationTo: 'cells';
        value: string | Cell;
      } | null)
    | ({
        relationTo: 'tariffs';
        value: string | Tariff;
      } | null)
    | ({
        relationTo: 'subscriptions';
        value: string | Subscription;
      } | null)
    | ({
        relationTo: 'payments';
        value: string | Payment;
      } | null)
    | ({
        relationTo: 'support-tickets';
        value: string | SupportTicket;
      } | null)
    | ({
        relationTo: 'support-messages';
        value: string | SupportMessage;
      } | null)
    | ({
        relationTo: 'integration-events';
        value: string | IntegrationEvent;
      } | null)
    | ({
        relationTo: 'audit-log';
        value: string | AuditLog;
      } | null)
    | ({
        relationTo: 'otp-challenges';
        value: string | OtpChallenge;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  phone?: T;
  firstName?: T;
  lastName?: T;
  contactEmail?: T;
  role?: T;
  active?: T;
  notifications?: T;
  paymentBrand?: T;
  paymentLast4?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "storage-items_select".
 */
export interface StorageItemsSelect<T extends boolean = true> {
  owner?: T;
  internalID?: T;
  title?: T;
  type?: T;
  description?: T;
  contents?: T;
  barcode?: T;
  seal?: T;
  status?: T;
  cell?: T;
  monthlyPrice?: T;
  startedAt?: T;
  media?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  owner?: T;
  number?: T;
  type?: T;
  status?: T;
  items?: T;
  fulfillment?: T;
  address?: T;
  slot?: T;
  assignee?: T;
  picked?: T;
  signature?: T;
  evidence?: T;
  idempotencyKey?: T;
  requestHash?: T;
  payment?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order-events_select".
 */
export interface OrderEventsSelect<T extends boolean = true> {
  owner?: T;
  order?: T;
  status?: T;
  actor?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "warehouses_select".
 */
export interface WarehousesSelect<T extends boolean = true> {
  name?: T;
  address?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cells_select".
 */
export interface CellsSelect<T extends boolean = true> {
  name?: T;
  warehouse?: T;
  zone?: T;
  barcode?: T;
  capacity?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tariffs_select".
 */
export interface TariffsSelect<T extends boolean = true> {
  name?: T;
  code?: T;
  kind?: T;
  itemType?: T;
  testOnly?: T;
  monthlyPrice?: T;
  itemLimit?: T;
  rules?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriptions_select".
 */
export interface SubscriptionsSelect<T extends boolean = true> {
  owner?: T;
  tariff?: T;
  status?: T;
  nextChargeAt?: T;
  providerCustomerID?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payments_select".
 */
export interface PaymentsSelect<T extends boolean = true> {
  owner?: T;
  amount?: T;
  status?: T;
  provider?: T;
  providerID?: T;
  idempotencyKey?: T;
  order?: T;
  tariff?: T;
  receiptURL?: T;
  paidAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "support-tickets_select".
 */
export interface SupportTicketsSelect<T extends boolean = true> {
  owner?: T;
  type?: T;
  subject?: T;
  status?: T;
  order?: T;
  item?: T;
  attachments?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "support-messages_select".
 */
export interface SupportMessagesSelect<T extends boolean = true> {
  owner?: T;
  ticket?: T;
  author?: T;
  authorRole?: T;
  text?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "integration-events_select".
 */
export interface IntegrationEventsSelect<T extends boolean = true> {
  key?: T;
  provider?: T;
  status?: T;
  externalID?: T;
  entityID?: T;
  errorCode?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-log_select".
 */
export interface AuditLogSelect<T extends boolean = true> {
  actor?: T;
  entity?: T;
  entityID?: T;
  action?: T;
  changedFields?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "otp-challenges_select".
 */
export interface OtpChallengesSelect<T extends boolean = true> {
  phoneKey?: T;
  ipKey?: T;
  hash?: T;
  expiresAt?: T;
  attempts?: T;
  consumed?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  owner?: T;
  purpose?: T;
  prefix?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSend-otp".
 */
export interface TaskSendOtp {
  input: {
    challengeID: string;
    phone: string;
  };
  output: {
    sent: boolean;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}